### ISSUE TITLE
Feature request: preserve comments

### ISSUE THREAD

**Issue by elliotwaite** [bram209/leptosfmt#15] opened 2023-03-28 04:58 UTC
The formatter currently removes comments. It would be nice to have the option to preserve comments (or perhaps this could be made the default behavior).

**Comment by bram209** [comment] 2023-03-28 08:51
duplicate of #3

**Closed by bram209** 2023-03-28 08:51 UTC

**Comment by elliotwaite** [comment] 2023-03-28 21:20
Ah, got it, thanks.

Sorry for forgetting to check for duplicates before posting this. I'll make sure to do so in the future.

**Comment by bram209** [comment] 2023-03-28 22:36
No problem! L
