### ISSUE TITLE
Rust fmt and leptosfmt have different opinions

### ISSUE THREAD

**Issue by johan-smits** [bram209/leptosfmt#54] opened 2023-07-28 10:02 UTC
When I have a component that is formatted with cargo-fmt:

```rs
// Valid Rust formatted code
#[component]
pub(crate) fn Error(cx: Scope, message: Option<String>) -> impl IntoView {
    view! { cx,
      <div>
        Example
      </div>
    }
}
```

When I format this with `leptosfmt` (`0.1.11`) It gives me a diff:

```diff
 pub(crate) fn Error(cx: Scope, message: Option<String>) -> impl IntoView {
     view! { cx,
-      <div>
-        Example
-      </div>
-    }
+    <div>
+      Example
+    </div>
+  }
 }
```

When I run the Rust format it changes it back again, since in our CI we test for cragofmt validation it fails if we use `leptosfmt`. It seems not to see the offset of the view starting position of the view and does not uses it to compensate it.

**Comment by bram209** [comment] 2023-07-28 11:15
hmm odd,

The following test passes:

```rust
    #[test]
    fn rustfmt_missmatch() {
        let source = indoc! {r#"
        // Valid Rust formatted code
        #[component]
        pub(crate) fn Error(cx: Scope, message: Option<String>) -> impl IntoView {
            view! { cx,
              <div>
                Example
              </div>
            }
        }
        "#};

        let result = format_file_source(source, Default::default()).unwrap();
        insta::assert_snapshot!(result, @r###"
        // Valid Rust formatted code
        #[component]
        pub(crate) fn Error(cx: Scope, message: Option<String>) -> impl IntoView {
            view! { cx,
                <div>
                    Example
                </div>
            }
        }
        "###);
    }
```

**Comment by bram209** [comment] 2023-07-28 11:17
if you are happy with the way `leptosfmt` formats things, you could disable body formatting for the `view` macro in rustfmt: https://rust-lang.github.io/rustfmt/?version=master&search=macro#skip_macro_invocations

**Comment by johan-smits** [comment] 2023-07-28 11:33
@bram209 I have `tab_spaces = 2` set in the toml. I thought this has only effect inside the view and not the view macro itself.
When i set it to 4 it is correct.

**Comment by johan-smits** [comment] 2023-07-28 11:38
You can reproduce it with this test:

```rs
   #[test]
    fn rustfmt_missmatch() {
        let source = indoc! {r#"
        // Valid Rust formatted code
        #[component]
        pub(crate) fn Error(cx: Scope, message: Option<String>) -> impl IntoView {
            view! { cx,
              <div>
                Example
              </div>
            }
        }
        "#};

        let result = format_file_source(source, FormatterSettings{tab_spaces: 2, ..Default::default()}).unwrap();
        insta::assert_snapshot!(result, @r###"
        // Valid Rust formatted code
        #[component]
        pub(crate) fn Error(cx: Scope, message: Option<String>) -> impl IntoView {
            view! { cx,
              <div>
                Example
              </div>
            }
        }
        "###);
    }
```

**Comment by bram209** [comment] 2023-07-28 11:43
> @bram209 I have `tab_spaces = 2` set in the toml. I thought this has only effect inside the view and not the view macro itself. When i set it to 4 it is correct.

You either need to align the tab spaces with rustfmt or configure rustfmt to not format the macro body with this configuration option: https://rust-lang.github.io/rustfmt/?version=master&search=macro#skip_macro_invocations

The current behaviour works as intended, so can I close this issue?

**Comment by johan-smits** [comment] 2023-07-28 12:02
If the answer to the next question is no you can close it.

Can `leptosfmt` see the number of spaces that where used for the initial macro start position and add that as a baseline? Like this you can position the initial macro anywhere you want and `leptosfmt` will format relative to this position. Like this it does not matter if you have different settings for `rustfmt` and `leptosfmt`.

Did you notice that the `}` of the view is also changed with `leptosfmt` and what I expected that it should do this right? By changing the position of the view `}` `rustfmt` also moves the body. See here the gif when I change the `}` and rustfmt after this.

![Peek 2023-07-28 14-00](https://github.com/bram209/leptosfmt/assets/3228882/07d6ca6f-6c87-4633-be66-3ef59c962f29)
In the gif I'm simulating by hand what is causing by`leptosfmt`.

So if `leptosfmt` don't changes the `}` of the view or uses the same start position of the `view` macro for this closing bracket it works fine with 2 different settings.

**Comment by bram209** [comment] 2023-07-28 12:05
In your gif, are you running rustfmt or leptosfmt?

**Comment by johan-smits** [comment] 2023-07-28 12:08
I run `rustfmt`. But the manual action I do removing the 2 spaces is what `leptosfmt` does (and also the body but that does not matter).

**Comment by johansmitsnl** [comment] 2023-07-29 07:39
The red is the auto-detect format, then green is when rust format runs:

```diff
     let title = if people.len() > 1 {
         view! {
-      <h2 class="text-3xl font-bold mb-12">
-        "Meet the " <span class="text-blue-600">"team"</span>
-      </h2>
-    }
+          <h2 class="text-3xl font-bold mb-12">
+            "Meet the " <span class="text-blue-600">"team"</span>
+          </h2>
+        }
     }
```

I don't know a lot of the internals, but can you see the position where `view!` starts on how many spaces this begins and use this as the offset?

**Comment by bram209** [comment] 2023-07-29 09:35
> the position where view! starts on how many spaces this begins and use this as the offset

That is what I was doing before, but then you get issues like #20

I have to walk through the rust source code and somehow infer what the right indentation is, which is a pain in the ass.

**Comment by awesomelemonade** [comment] 2023-07-29 19:37
> > the position where view! starts on how many spaces this begins and use this as the offset
> 
> That is what I was doing before, but then you get issues like #20
> 
> I have to walk through the rust source code and somehow infer what the right indentation is, which is a pain in the ass.

Not sure what you did before, but what you can try is locate the start byte (like here: https://github.com/bram209/leptosfmt/blob/a2b20ec66038ee5f515c7f36f83367cb8fdec471/formatter/src/source_file.rs#L49C13-L49C24) then find the byte index of the previous newline character, then copy the whitespace characters (tabs, spaces) that are directly after the newline character.

I do something similar in this project: https://github.com/awesomelemonade/expect-tests/blob/7ecf6a7a417ad44f93b52b2b99e2715ad5a2de62/src/lib.rs#L219
though looking back on it now, I should've included all whitespaces instead of just spaces.

**Comment by bram209** [comment] 2023-07-30 13:47
> > > the position where view! starts on how many spaces this begins and use this as the offset
> > 
> > 
> > That is what I was doing before, but then you get issues like #20
> > I have to walk through the rust source code and somehow infer what the right indentation is, which is a pain in the ass.
> 
> Not sure what you did before, but what you can try is locate the start byte (like here: https://github.com/bram209/leptosfmt/blob/a2b20ec66038ee5f515c7f36f83367cb8fdec471/formatter/src/source_file.rs#L49C13-L49C24) then find the byte index of the previous newline character, then copy the number of spaces that are directly after the newline character.
> 
> I do something similar in this project: https://github.com/awesomelemonade/expect-tests/blob/7ecf6a7a417ad44f93b52b2b99e2715ad5a2de62/src/lib.rs#L219 though looking back on it now, maybe I should've supported tabs? ehh rust uses spaces anyways

Hmm that could work, that would also fix the other issue. I will give this approach a try

**Comment by bram209** [comment] 2023-07-30 14:03
@johan-smits could you try to install: `cargo install --git https://github.com/bram209/leptosfmt.git --branch fix-view-indentation-issues` and let me know if that fixes your problem?

**Comment by johansmitsnl** [comment] 2023-07-30 18:06
@bram209 this works :+1:

**Closed** 2023-07-31 08:49 UTC
