### ISSUE TITLE
Leptosfmt messes up the formatting of everything inside macros other than view!

### ISSUE THREAD

**Issue by stevepryde** [bram209/leptosfmt#104] opened 2024-02-08 23:43 UTC
Leptosfmt seems to destroy the formatting of anything inside macros other than the `view!` macro.

Examples:
```
classes!(
    "example-1", intent, size, icon_only.get().then_some("btn-icon-only"), wide
    .get().then_some("w-full"), is_focus.get()
    .then_some("focus:shadow-5xl"), class
)
```

and this (a wrapper that also happens to contain html, except now leptosfmt breaks it):
```
example! {
    < Search search_icon = { view! { < IconSearch class = "text-grey-800" /> } }
    />
}
```

I think leptosfmt should never touch any code that is inside another macro, even if it "looks like" html.

**Comment by bram209** [comment] 2024-02-14 10:58
duplicate of #97

Indeed, it would be better to keep the original source instead. The behaviour that you see currently is from the `prettyplease` crate. However, I maintain a fork and will change this so that the original formatting is preserved.

**Closed by bram209** 2024-02-14 10:58 UTC
