### ISSUE TITLE
missing `class_wrapping` when installing

### ISSUE THREAD

**Issue by Arend-Jan** [bram209/leptosfmt#154] opened 2024-10-22 08:19 UTC
Command run
```zsh
cargo install leptosfmt
```

Result
```zsh
error[E0063]: missing field `class_wrapping` in initializer of `Options`
 --> /Users/my-user-name/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptosfmt-formatter-0.1.32/src/formatter/tailwind.rs:7:43
  |
7 |         static OPTIONS: sorter::Options = sorter::Options {
  |                                           ^^^^^^^^^^^^^^^ missing `class_wrapping`

For more information about this error, try `rustc --explain E0063`.
error: could not compile `leptosfmt-formatter` (lib) due to 1 previous error
```

System
```
Rustc:
rustc 1.84.0-nightly (439284741 2024-10-21)
binary: rustc
commit-hash: 4392847410ddd67f6734dd9845f9742ff9e85c83
commit-date: 2024-10-21
host: aarch64-apple-darwin
release: 1.84.0-nightly
LLVM version: 19.1.1

Cargo:
cargo 1.84.0-nightly (cf53cc54b 2024-10-18)
release: 1.84.0-nightly
commit-hash: cf53cc54bb593b5ec3dc2be4b1702f50c36d24d5
commit-date: 2024-10-18
host: aarch64-apple-darwin
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.7.1 (sys:0.4.74+curl-8.9.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 15.0.1 [64-bit]

Rustup:
Default host: aarch64-apple-darwin

installed toolchains
--------------------

stable-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
wasm32-unknown-unknown

active toolchain
----------------

nightly-aarch64-apple-darwin (directory override for 'somedir')
rustc 1.84.0-nightly (439284741 2024-10-21)

Software:

    System Software Overview:

      System Version: macOS 15.0.1 (24A348)
      Kernel Version: Darwin 24.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,1
      Model Number: Z14V000QFN/A
      Chip: Apple M1 Pro
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 32 GB
      System Firmware Version: 11881.1.1
      OS Loader Version: 11881.1.1
```

**Comment by ilyvion** [comment] 2024-10-22 10:37
Running it as `cargo install leptosfmt --locked` resolved this for me. Which suggests that this was probably caused by a dependency making a breaking change without appropriately updating their version number.

**Comment by ilyvion** [comment] 2024-10-22 10:53
Seems to be a breaking change caused by rustywind_core between v0.1.3 and v0.1.4. I reported it @ avencera/rustywind#111. `--locked` works because it uses v0.1.2.

**Comment by praveenperera** [comment] 2024-10-23 01:57
sorry about that everyone, I've yanked the offending version and it should work now

**Comment by bram209** [comment] 2024-10-23 08:48
thanks for reporting it and thanks for your quick repsonse @praveenperera 

I will close this issue as completed

**Closed by bram209** 2024-10-23 08:48 UTC
